version: '3.9'

services:
  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: zamotaeff/todoisto
    restart: always
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
  migrations:
    build: .
    image: zamotaeff/todoisto
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    command: > 
      sh -c "python3 manage.py migrate"
  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
