version: '3.9'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      -  postgres_data:/var/lib/postgresql/data/
    env_file: .env.prod
    restart: always
    ports:
    - "5432:5432"
  web:
    build: .
    command: gunicorn todoisto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env.prod
    depends_on:
      - db

volumes:
  postgres_data:
